"""exempt niquesness

Revision ID: 4192f94455f9
Revises: daa25e272243
Create Date: 2024-08-29 22:51:43.608436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4192f94455f9'
down_revision: Union[str, None] = 'daa25e272243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('warehouses_Warehouselocation_id_key', 'warehouses', type_='unique')
    op.drop_constraint('warehouses_Warehousephone_id_key', 'warehouses', type_='unique')
    op.drop_constraint('warehouses_Warehousepostal_id_key', 'warehouses', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('warehouses_Warehousepostal_id_key', 'warehouses', ['Warehousepostal_id'])
    op.create_unique_constraint('warehouses_Warehousephone_id_key', 'warehouses', ['Warehousephone_id'])
    op.create_unique_constraint('warehouses_Warehouselocation_id_key', 'warehouses', ['Warehouselocation_id'])
    # ### end Alembic commands ###
