"""model built

Revision ID: daa25e272243
Revises: f8310c54da76
Create Date: 2024-08-16 05:52:33.655845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daa25e272243'
down_revision: Union[str, None] = 'f8310c54da76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ccnics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnic', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ccnics_cnic'), 'ccnics', ['cnic'], unique=True)
    op.create_index(op.f('ix_ccnics_id'), 'ccnics', ['id'], unique=False)
    op.create_table('cemails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cemails_email'), 'cemails', ['email'], unique=True)
    op.create_index(op.f('ix_cemails_id'), 'cemails', ['id'], unique=False)
    op.create_table('deliverystatuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliverystatuses_id'), 'deliverystatuses', ['id'], unique=False)
    op.create_index(op.f('ix_deliverystatuses_status'), 'deliverystatuses', ['status'], unique=False)
    op.create_table('fragiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fragileyesno', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fragiles_fragileyesno'), 'fragiles', ['fragileyesno'], unique=False)
    op.create_index(op.f('ix_fragiles_id'), 'fragiles', ['id'], unique=False)
    op.create_table('mediumtypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mediumtypes_id'), 'mediumtypes', ['id'], unique=False)
    op.create_index(op.f('ix_mediumtypes_type'), 'mediumtypes', ['type'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('totalprice', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_quantity'), 'orders', ['quantity'], unique=False)
    op.create_index(op.f('ix_orders_totalprice'), 'orders', ['totalprice'], unique=False)
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stateyn', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_states_id'), 'states', ['id'], unique=False)
    op.create_index(op.f('ix_states_stateyn'), 'states', ['stateyn'], unique=False)
    op.create_table('warehouselocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouselocations_id'), 'warehouselocations', ['id'], unique=False)
    op.create_index(op.f('ix_warehouselocations_location'), 'warehouselocations', ['location'], unique=False)
    op.create_table('warehousephones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehousephones_id'), 'warehousephones', ['id'], unique=False)
    op.create_index(op.f('ix_warehousephones_phone'), 'warehousephones', ['phone'], unique=False)
    op.create_table('warehousepostals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postal', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehousepostals_id'), 'warehousepostals', ['id'], unique=False)
    op.create_index(op.f('ix_warehousepostals_postal'), 'warehousepostals', ['postal'], unique=False)
    op.create_table('weathertypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Weather', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weathertypes_Weather'), 'weathertypes', ['Weather'], unique=False)
    op.create_index(op.f('ix_weathertypes_id'), 'weathertypes', ['id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('Cemail_id', sa.Integer(), nullable=True),
    sa.Column('Ccnic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Ccnic_id'], ['ccnics.id'], ),
    sa.ForeignKeyConstraint(['Cemail_id'], ['cemails.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Ccnic_id'),
    sa.UniqueConstraint('Cemail_id')
    )
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=True)
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daddress', sa.String(), nullable=False),
    sa.Column('dtime', sa.String(), nullable=False),
    sa.Column('ddate', sa.String(), nullable=False),
    sa.Column('Deliverystatus_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Deliverystatus_id'], ['deliverystatuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliveries_daddress'), 'deliveries', ['daddress'], unique=False)
    op.create_index(op.f('ix_deliveries_ddate'), 'deliveries', ['ddate'], unique=False)
    op.create_index(op.f('ix_deliveries_dtime'), 'deliveries', ['dtime'], unique=False)
    op.create_index(op.f('ix_deliveries_id'), 'deliveries', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('State_id', sa.Integer(), nullable=True),
    sa.Column('Fragile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Fragile_id'], ['fragiles.id'], ),
    sa.ForeignKeyConstraint(['State_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_price'), 'products', ['price'], unique=False)
    op.create_index(op.f('ix_products_weight'), 'products', ['weight'], unique=False)
    op.create_table('tmediums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('weightlimit', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('Mediumtype_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Mediumtype_id'], ['mediumtypes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tmediums_id'), 'tmediums', ['id'], unique=False)
    op.create_index(op.f('ix_tmediums_name'), 'tmediums', ['name'], unique=False)
    op.create_index(op.f('ix_tmediums_quantity'), 'tmediums', ['quantity'], unique=False)
    op.create_index(op.f('ix_tmediums_speed'), 'tmediums', ['speed'], unique=False)
    op.create_index(op.f('ix_tmediums_weightlimit'), 'tmediums', ['weightlimit'], unique=False)
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('Warehousepostal_id', sa.Integer(), nullable=True),
    sa.Column('Warehouselocation_id', sa.Integer(), nullable=True),
    sa.Column('Warehousephone_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Warehouselocation_id'], ['warehouselocations.id'], ),
    sa.ForeignKeyConstraint(['Warehousephone_id'], ['warehousephones.id'], ),
    sa.ForeignKeyConstraint(['Warehousepostal_id'], ['warehousepostals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Warehouselocation_id'),
    sa.UniqueConstraint('Warehousephone_id'),
    sa.UniqueConstraint('Warehousepostal_id')
    )
    op.create_index(op.f('ix_warehouses_id'), 'warehouses', ['id'], unique=False)
    op.create_index(op.f('ix_warehouses_name'), 'warehouses', ['name'], unique=False)
    op.create_table('weatherdatas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('humidity', sa.Integer(), nullable=False),
    sa.Column('pressure', sa.Integer(), nullable=False),
    sa.Column('wind', sa.Integer(), nullable=False),
    sa.Column('Weathertype_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Weathertype_id'], ['weathertypes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weatherdatas_date'), 'weatherdatas', ['date'], unique=False)
    op.create_index(op.f('ix_weatherdatas_humidity'), 'weatherdatas', ['humidity'], unique=False)
    op.create_index(op.f('ix_weatherdatas_id'), 'weatherdatas', ['id'], unique=False)
    op.create_index(op.f('ix_weatherdatas_pressure'), 'weatherdatas', ['pressure'], unique=False)
    op.create_index(op.f('ix_weatherdatas_wind'), 'weatherdatas', ['wind'], unique=False)
    op.create_table('cphones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=12), nullable=False),
    sa.Column('Customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cphones_id'), 'cphones', ['id'], unique=False)
    op.create_index(op.f('ix_cphones_phone'), 'cphones', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cphones_phone'), table_name='cphones')
    op.drop_index(op.f('ix_cphones_id'), table_name='cphones')
    op.drop_table('cphones')
    op.drop_index(op.f('ix_weatherdatas_wind'), table_name='weatherdatas')
    op.drop_index(op.f('ix_weatherdatas_pressure'), table_name='weatherdatas')
    op.drop_index(op.f('ix_weatherdatas_id'), table_name='weatherdatas')
    op.drop_index(op.f('ix_weatherdatas_humidity'), table_name='weatherdatas')
    op.drop_index(op.f('ix_weatherdatas_date'), table_name='weatherdatas')
    op.drop_table('weatherdatas')
    op.drop_index(op.f('ix_warehouses_name'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_id'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_tmediums_weightlimit'), table_name='tmediums')
    op.drop_index(op.f('ix_tmediums_speed'), table_name='tmediums')
    op.drop_index(op.f('ix_tmediums_quantity'), table_name='tmediums')
    op.drop_index(op.f('ix_tmediums_name'), table_name='tmediums')
    op.drop_index(op.f('ix_tmediums_id'), table_name='tmediums')
    op.drop_table('tmediums')
    op.drop_index(op.f('ix_products_weight'), table_name='products')
    op.drop_index(op.f('ix_products_price'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_deliveries_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_dtime'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_ddate'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_daddress'), table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_weathertypes_id'), table_name='weathertypes')
    op.drop_index(op.f('ix_weathertypes_Weather'), table_name='weathertypes')
    op.drop_table('weathertypes')
    op.drop_index(op.f('ix_warehousepostals_postal'), table_name='warehousepostals')
    op.drop_index(op.f('ix_warehousepostals_id'), table_name='warehousepostals')
    op.drop_table('warehousepostals')
    op.drop_index(op.f('ix_warehousephones_phone'), table_name='warehousephones')
    op.drop_index(op.f('ix_warehousephones_id'), table_name='warehousephones')
    op.drop_table('warehousephones')
    op.drop_index(op.f('ix_warehouselocations_location'), table_name='warehouselocations')
    op.drop_index(op.f('ix_warehouselocations_id'), table_name='warehouselocations')
    op.drop_table('warehouselocations')
    op.drop_index(op.f('ix_states_stateyn'), table_name='states')
    op.drop_index(op.f('ix_states_id'), table_name='states')
    op.drop_table('states')
    op.drop_index(op.f('ix_orders_totalprice'), table_name='orders')
    op.drop_index(op.f('ix_orders_quantity'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_mediumtypes_type'), table_name='mediumtypes')
    op.drop_index(op.f('ix_mediumtypes_id'), table_name='mediumtypes')
    op.drop_table('mediumtypes')
    op.drop_index(op.f('ix_fragiles_id'), table_name='fragiles')
    op.drop_index(op.f('ix_fragiles_fragileyesno'), table_name='fragiles')
    op.drop_table('fragiles')
    op.drop_index(op.f('ix_deliverystatuses_status'), table_name='deliverystatuses')
    op.drop_index(op.f('ix_deliverystatuses_id'), table_name='deliverystatuses')
    op.drop_table('deliverystatuses')
    op.drop_index(op.f('ix_cemails_id'), table_name='cemails')
    op.drop_index(op.f('ix_cemails_email'), table_name='cemails')
    op.drop_table('cemails')
    op.drop_index(op.f('ix_ccnics_id'), table_name='ccnics')
    op.drop_index(op.f('ix_ccnics_cnic'), table_name='ccnics')
    op.drop_table('ccnics')
    # ### end Alembic commands ###
