"""eliminated name from tmediums

Revision ID: eb43dd07fcb2
Revises: 4192f94455f9
Create Date: 2024-08-30 03:18:28.835593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb43dd07fcb2'
down_revision: Union[str, None] = '4192f94455f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tmediums_name', table_name='tmediums')
    op.drop_column('tmediums', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tmediums', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_tmediums_name', 'tmediums', ['name'], unique=False)
    # ### end Alembic commands ###
